spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Welcome1

  sql:
    init:
      mode: always
