CREATE DATABASE PHASE3_PROJECT_SPORTY_SHOES;

USE PHASE3_PROJECT_SPORTY_SHOES;

CREATE TABLE ADMIN_CONFIG (
    ADMIN_ID        VARCHAR(20)		NOT NULL,
    USER_NAME       VARCHAR(50)		NOT NULL,
    PASSWORD        VARCHAR(15)		NOT NULL,
    CONSTRAINT PK_ADMIN_CFG PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE USER_CONFIG (
    USER_ID             VARCHAR(20)		NOT NULL,
    FIRST_NAME			VARCHAR(30)		NOT NULL,
	MIDDLE_NAME			VARCHAR(30),
	LAST_NAME		    VARCHAR(30),
	EMAIL				VARCHAR(50)		NOT NULL,
    ADDRESS             VARCHAR(100)    NOT NULL,
    AGE                 SMALLINT        NOT NULL,
    PASSWORD            VARCHAR(15)		NOT NULL,
    CONSTRAINT PK_USER_CFG PRIMARY KEY (USER_ID)
);

CREATE INDEX IDX_USER_CONFIG_01 ON USER_CONFIG (EMAIL);

CREATE TABLE PRODUCT_CATEGORY (
    CATEGORY_ID     MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME   VARCHAR(50)	    NOT NULL,
    CONSTRAINT PK_PROD_CAT PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID      MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    CATEGORY_ID     MEDIUMINT       NOT NULL,
    PRODUCT_NAME    VARCHAR(75)		NOT NULL,
    PRICE			FLOAT			NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (CATEGORY_ID) 
        REFERENCES PRODUCT_CATEGORY (CATEGORY_ID)
);

CREATE INDEX IDX_PRODUCT_01 ON PRODUCT (CATEGORY_ID); 

CREATE TABLE PURCHASE (
    PURCHASE_ID     MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    USER_ID         VARCHAR(20)		NOT NULL,
    GROSS_TOTAL     FLOAT           NOT NULL,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (PURCHASE_ID),
    CONSTRAINT FK_PURCHASE FOREIGN KEY (USER_ID) 
        REFERENCES USER_CONFIG (USER_ID)
);

CREATE INDEX IDX_PURCHASE_01 ON PURCHASE (USER_ID); 

CREATE TABLE PURCHASE_ITEMS (
    PURCHASE_ITEM_ID    MEDIUMINT 		NOT NULL AUTO_INCREMENT,
    PURCHASE_ID         MEDIUMINT 		NOT NULL,
    PRODUCT_ID          MEDIUMINT 		NOT NULL,
    QUANTITY            SMALLINT        NOT NULL,
    CONSTRAINT PK_PURCHASE_ITEMS PRIMARY KEY (PURCHASE_ITEM_ID),
    CONSTRAINT FK_PURCHASE_ITEMS_01 FOREIGN KEY (PURCHASE_ID) 
        REFERENCES PURCHASE (PURCHASE_ID),
    CONSTRAINT FK_PURCHASE_ITEMS_02 FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE INDEX IDX_PURCHASE_ITEMS_01 ON PURCHASE_ITEMS (PURCHASE_ID);
CREATE INDEX IDX_PURCHASE_ITEMS_02 ON PURCHASE_ITEMS (PRODUCT_ID);

